### PR TITLE
find_all_factors_of_numbers.py added to folder with changes in readme.md

### PR DESCRIPTION
**Pull request by Saloni-prsd**

### CODE REVIEW

**Comment by aryadas98** [comment]
Please make a folder for the adam numbers files and move all the files there.

**Comment by aryadas98** [comment]
I don't see any PRs. Can you please specify their numbers?

**Comment by Saloni-prsd** [comment]
#1 PR from feature-2
#2 from Saloni-prsd-patch-1
#3  from Saloni-prsd-patch-2

**Comment by Saloni-prsd** [comment]
@aryadas98  please review the pr

**Comment by aryadas98** [comment]
#1, #2 and #3 are not new PRs. They have been closed/merged long ago. Now that the coding period is over, to get points for your work, you must update this PR and not open new PRs. To update this PR, you have to make changes to this branch (that is Saloni-prsd:feature). It is even mentioned by GitHub below.

image

**Comment by aryadas98** [comment]
Do this change by tomorrow because we have to finalize the leaderboard soon.

**Pull request closed without merging**
