### PR TITLE
Add magic_no algorithm in c and update readme

### PR DESCRIPTION
**Pull request by PavitKaur05**

### CODE REVIEW

**Comment by aryadas98** [comment]
@PavitKaur05 The folder structure has changed. Please update this PR.

**Comment by PavitKaur05** [comment]
@aryadas98  Sorry I am new to this . I did not understand what you meant  please will you explain??

**Comment by aryadas98** [comment]
It means that you have to push a new commit to the branch from where this PR was opened. That will update the PR. In your case, push a new commit to this branch - PavitKaur05:new.

**Comment by aryadas98** [comment]
Done in #95

**Pull request closed without merging**
