### PR TITLE
Rabin-Karp & Naive pattern searching algorithm & remove duplicates from sorted array

### PR DESCRIPTION
**Pull request by saurabhshadow**

### CODE REVIEW

**Comment by saurabhshadow** [comment]
I have also added **Rabin-Karp Algorithm**, implemented in C & C++.

**Comment by CoderJolly** [comment]
Closes: #137

**Comment by aryadas98** [comment]
Good job!

**Comment by CoderJolly** [comment]
I am nt sure how the issue has to be closed, pls guide me @aryadas98

**Comment by aryadas98** [comment]
@CoderJolly you have to write Fixes #137

**Pull request merged**
